packages:
  - 'apps/*'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.102.3'
  - '@tanstack/query-devtools@5.102.3'
  - '@tanstack/react-query-devtools@5.102.3'
  - '@tanstack/react-query@5.102.3'
  - '@types/node@26.3.0'
  - mongoose@9.9.4
